booking/urls.py
from django.urls import path
from .views import booking_list, schedule_booking, available_times_ajax, booking_search, booking_detail, tasker_reviews_ajax

app_name = 'booking'

urlpatterns = [
    path('booking_list/<int:_id>', booking_list, name="booking-list"),
    path('booking_search/<slug:category>', booking_search, name="booking-search"),
    path('booking_schedule/<int:_id>/<str:category>/', schedule_booking, name="schedule-booking"),
    path('booking_schedule/<int:_id>/<str:category>/ajax/booking', available_times_ajax, name="booking-times"),
    path('booking_detail/<int:id>/', booking_detail, name="booking-detail"),
    path('booking_search/ajax/reviews/<int:_id>/', tasker_reviews_ajax, name="tasker-reviews")
]

chat/urls.py
from django.urls import path
from .views import messages, messages_json, send_message_json, message_home

app_name = 'chat'

urlpatterns = [
    path('', message_home, name="message-home"),
    path('<int:booking_id>', messages, name="my-messages"), 
    path('messages/json/<int:booking_id>', messages_json, name="json-messages"),
    path('messages/json/send_message/<int:booking_id>', send_message_json, name="messages-send")

]

taskusagi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls')),
    path('bookings/', include('booking.urls')),
    path('chat/', include('chat.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import SignUpView, SeekerSignUpView, TaskerSignUpView, edit_profile, tasks, task_delete, dashboard, tasker_schedule,tasker_schedule_delete,todo_delete, tasker_profile_view

app_name = 'user'

urlpatterns = [
    path('dashboard/', dashboard, name="dashboard"), 
    path('dashboard/<int:todo_id>/', dashboard, name="dashboard"), 
    path('signup/', SignUpView.as_view(), name='signup'),
    path('seeker_signup/', SeekerSignUpView.as_view(), name='seeker-signup'),
    path('tasker_signup/', TaskerSignUpView.as_view(), name='tasker-signup'),
    path('profile_edit/', edit_profile, name='profile_edit'),
    path('tasker_tasks/', tasks, name='tasks'),
    path('tasker_schedule/', tasker_schedule, name='tasker-schedule'),
    path('tasker_task_delete/<int:_id>', task_delete, name='task-delete'),
    path('tasker_schedule_delete/<int:_id>', tasker_schedule_delete, name='tasker-schedule-delete'),
    path('tasker_profile/<int:_id>', tasker_profile_view, name='tasker-profile'),
    path('todo_delete/<int:id>/', todo_delete, name='todo-delete')
]

templates/utilities/_footer.html
{% load static %}

<footer class="page-footer font-small pt-4" >
    <div class="container-fluid text-center text-md-left">
      <div class="row">
        <div class="col-md-4 mt-md-0 mt-3">
          <!-- Content -->
          <h5 class="footer-header"><img class="header-icon" style="height: 50px;" src="{% static 'taskusagi/img/rabbit.svg' %}">TaskUsagi</h5>
        </div>
        <hr class="clearfix w-100 d-md-none pb-3">
        <div class="col-md-3 mb-md-0 mb-3">
          <h5 class="text-uppercase">Discover</h5>
          <ul class="list-unstyled">
            <li>
              <a href="#!">Become a tasker</a>
            </li>
            <li>
              <a href="#!">Buy a gift card</a>
            </li>
            <li>
              <a href="#!">Help</a>
            </li>
          </ul>
        </div>
        <div class="col-md-3 mb-md-0 mb-3">
          <h5 class="text-uppercase">Company</h5>
          <ul class="list-unstyled">
            <li>
              <a href="#!">About Us</a>
            </li>
            <li>
              <a href="#!">Careers</a>
            </li>
            <li>
              <a href="#!">Press</a>
            </li>
            <li>
              <a href="#!">Blog</a>
            </li>
            <li>
              <a href="#!">Terms & Privacy</a>
            </li>
          </ul>
        </div>
        <div class="col-md-2 mb-md-0 mb-3">
          <ul class="list-unstyled d-flex row">
            <li><a href=""><i class="fab fa-twitter fa-2x" style="margin: 0 10px;"></i></a></li>
            <li><a href=""><i class="fab fa-instagram fa-2x" style="margin: 0 10px;"></i></a></li>
            <li><a href=""><i class="fab fa-facebook-square fa-2x" style="margin: 0 10px;" ></i></a></li>
          </ul>
          </div>
      </div>
    </div>
  
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="#"> TaskUsagi.com</a>
    </div>
  
  </footer>

templates/utilities/_messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><strong>{{ message }}</strong></li>
    {% endfor %}
</ul>
{% endif %}

templates/utilities/_nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light mt-2">
    <a class="navbar-header-custom" href="{% url 'user:dashboard' %}"><img class="nav-header-icon" src="{% static 'taskusagi/img/rabbit.svg' %}">Task<span class="navbar-header-custom usagi">Usagi</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:profile_edit' %}">Edit Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'booking:booking-list' request.user.id %}">View my bookings</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'chat:message-home' %}">My Messages</a>
        </li>
            {% if request.user.is_tasker %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:tasks' %}">View Tasks</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:tasker-schedule' %}">My Schedule</a>
            </li>
            {% endif %}
          <li class="nav-item ml-3">
              <a class="nav-link btn btn-outline-primary" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item ml-3">
            <a class="nav-link btn btn-outline-primary" href="{% url 'login' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>