booking/urls.py
from django.urls import path
from .views import booking_list, schedule_booking, available_times_ajax, booking_search, booking_detail, tasker_reviews_ajax

app_name = 'booking'

urlpatterns = [
    path('booking_list/<int:_id>', booking_list, name="booking-list"),
    path('booking_search/<slug:category>', booking_search, name="booking-search"),
    path('booking_schedule/<int:_id>/<str:category>/', schedule_booking, name="schedule-booking"),
    path('booking_schedule/<int:_id>/<str:category>/ajax/booking', available_times_ajax, name="booking-times"),
    path('booking_detail/<int:id>/', booking_detail, name="booking-detail"),
    path('booking_search/ajax/reviews/<int:_id>/', tasker_reviews_ajax, name="tasker-reviews")
]

chat/urls.py
from django.urls import path
from .views import messages, messages_json, send_message_json, message_home

app_name = 'chat'

urlpatterns = [
    path('', message_home, name="message-home"),
    path('<int:booking_id>', messages, name="my-messages"), 
    path('messages/json/<int:booking_id>', messages_json, name="json-messages"),
    path('messages/json/send_message/<int:booking_id>', send_message_json, name="messages-send")

]

taskusagi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls')),
    path('bookings/', include('booking.urls')),
    path('chat/', include('chat.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import SignUpView, SeekerSignUpView, TaskerSignUpView, edit_profile, tasks, task_delete, dashboard, tasker_schedule,tasker_schedule_delete,todo_delete, tasker_profile_view

app_name = 'user'

urlpatterns = [
    path('dashboard/', dashboard, name="dashboard"), 
    path('dashboard/<int:todo_id>/', dashboard, name="dashboard"), 
    path('signup/', SignUpView.as_view(), name='signup'),
    path('seeker_signup/', SeekerSignUpView.as_view(), name='seeker-signup'),
    path('tasker_signup/', TaskerSignUpView.as_view(), name='tasker-signup'),
    path('profile_edit/', edit_profile, name='profile_edit'),
    path('tasker_tasks/', tasks, name='tasks'),
    path('tasker_schedule/', tasker_schedule, name='tasker-schedule'),
    path('tasker_task_delete/<int:_id>', task_delete, name='task-delete'),
    path('tasker_schedule_delete/<int:_id>', tasker_schedule_delete, name='tasker-schedule-delete'),
    path('tasker_profile/<int:_id>', tasker_profile_view, name='tasker-profile'),
    path('todo_delete/<int:id>/', todo_delete, name='todo-delete')
]

booking/models.py
import functools
from django.db import models
from django.core import serializers
from users.models import Tasker, TaskSeeker
from django.urls import reverse
from datetime import datetime


class ScheduleBooking(models.Model):
    tasker = models.ForeignKey('users.Tasker', on_delete=models.CASCADE)
    seeker = models.ForeignKey('users.TaskSeeker', on_delete=models.CASCADE)
    category = models.CharField(max_length=50)
    booking = models.DateTimeField()
    price = models.IntegerField()
    notes = models.TextField(max_length=200)
    completed = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('booking:booking-detail', kwargs={'id': self.id })

    @property
    def get_most_recent_message(self):
        return self.message_set.latest('message_created')

    @classmethod
    def get_bookings(cls, _id, date):
        test = cls.objects.filter(tasker=_id, booking__date=date)
        bookings_dict = []
        
        for item in test:
            bookings_dict.append(item.booking.time().strftime("%H:%M"))

        return bookings_dict

    @classmethod
    def get_month_earnings(cls, tasker):
        current_month_schedules = cls.objects.filter(tasker=tasker, booking__month=datetime.today().month)
        bookings_list = []
        for booking in current_month_schedules:
            bookings_list.append(booking.price)
            
        return functools.reduce(lambda a,b: a+b, bookings_list) if len(bookings_list) else 0

    def __str__(self):
        return 'Tasker: {}, Seeker: {}, Booking: {}'.format(self.tasker, self.seeker, self.booking)

REVIEW_CHOICES = [
    ('1', 1),
    ('2', 2),
    ('3', 3),
    ('4', 4),
    ('5', 5)
]

class ScheduleBookingReview(models.Model):
    schedule = models.ForeignKey('ScheduleBooking', on_delete=models.CASCADE)
    review = models.TextField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)
    rating = models.CharField(
        max_length=1,
        choices=REVIEW_CHOICES,
        default=3
    )

    def __str__(self):
        return 'Schedule Review: {}, Rating: {}'.format(self.schedule, self.rating)

booking/forms.py
from django import forms
from .models import ScheduleBooking, ScheduleBookingReview

class ScheduleBookingForm(forms.ModelForm):
    booking = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])

    class Meta:
        model = ScheduleBooking
        fields = ['booking', 'notes',]

class ScheduleBookingReviewForm(forms.ModelForm):

    class Meta:
        model = ScheduleBookingReview
        fields = ['review', 'completed', 'rating']

    def clean_completed(self):
        completed = self.cleaned_data['completed']
        if completed is False:
            raise forms.ValidationError('Please mark this schedule as completed in order to leave a review')

        return completed

booking/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test

from users.models import Schedule, TaskCanDo, Tasker, TaskSeeker
from users.decorators import seeker_required, tasker_required
from booking.models import ScheduleBooking, ScheduleBookingReview
from booking.forms import ScheduleBookingForm, ScheduleBookingReviewForm
from chat.models import Message
from .ratings import r
import datetime

@login_required
def booking_detail(request, id): 
    booking = ScheduleBooking.objects.get(id=id)
    review = ScheduleBookingReview.objects.filter(schedule=booking).first() if booking.completed else None

    if request.method == 'POST':
        form = ScheduleBookingReviewForm(request.POST)
        if form.is_valid():
            booking_review = form.save(commit=False)
            booking_review.schedule = booking
            booking.completed = True
            booking.save()
            booking_review.save()

            # Update redis 
            form_rating = form.cleaned_data['rating']
            rating_count = r.incr('tasker:{}:recom_count'.format(booking.tasker.user.id))
            rating = r.incr('tasker:{}:recom_total'.format(booking.tasker.user.id), amount=form_rating)
            r.incr('tasker:{}:completed_tasks'.format(booking.tasker.user.id))
            
            # Calculate and set tasker review rating and add to completed tasks
            tasker = Tasker.objects.get(user=booking.tasker.user.id)
            tasker.rating = (rating / rating_count)
            tasker.completed += 1
            tasker.save()
            
            messages.add_message(request, messages.SUCCESS, 'Thanks for reviewing your tasker!')
            return redirect(reverse('booking:booking-list', kwargs={'_id': request.user.id}))
    else:
        form = ScheduleBookingReviewForm

    return render(request, 'booking/booking_detail.html', {'booking': booking, 'form': form, 'review': review })

@login_required
def booking_list(request, _id):
    bookings = None

    if request.user.is_tasker:
        bookings = ScheduleBooking.objects.filter(tasker=_id)
    else:
        bookings = ScheduleBooking.objects.filter(seeker=_id)

    bookings = bookings.order_by('-booking')

    return render(request, 'booking/booking_list.html', {'bookings': bookings})

@login_required
@user_passes_test(seeker_required)
def booking_search(request, category):
    results = TaskCanDo.objects.filter(category=category)
    category_name = results[0].catagory_display() if results else None
    time_pref = request.GET.get('task-time')
    price = request.GET.get('price')

    time_morning_1 = datetime.time(9,0,0)
    time_morning_2 = datetime.time(12,0,0)

    time_afternoon_1 = datetime.time(12,0,0)
    time_afternoon_2 = datetime.time(17,0,0)

    time_evening_1 = datetime.time(15,0,0)
    time_evening_2 = datetime.time(20,0,0)

    if time_pref == 'morning':
        results = results.filter(tasker__schedule__start_time__range=(time_morning_1, time_morning_2)).distinct()
    elif time_pref == 'afternoon':
        results = results.filter(tasker__schedule__start_time__range=(time_afternoon_1, time_afternoon_2)).distinct()
    elif time_pref == 'evening':
        results = results.filter(tasker__schedule__start_time__range=(time_evening_1, time_evening_2)).distinct()
    else:
        pass

    results = results.order_by('-price') if price == 'high' else results.order_by('price')

    return render(request, 'booking/booking_search.html', {'results': results, 'category_name': category_name})

@login_required
@user_passes_test(seeker_required)
def schedule_booking(request, _id, category):
    day_arr = Schedule.get_unavailable_days(_id)
    form_cat = None

    for cat in TaskCanDo.TASK_CHOICES:
        if category in cat:
            form_cat = cat[1]

    if request.method == 'POST':
        form = ScheduleBookingForm(request.POST)
        if form.is_valid():
            # Create a new booking
            booking = form.save(commit=False)

            booking.category = form_cat
            booking.tasker = Tasker.objects.get(user=_id)
            booking.seeker = TaskSeeker.objects.get(user=request.user.id)
            booking.price = TaskCanDo.objects.filter(tasker=Tasker.objects.get(user=_id)).first().price

            booking.save()
            # Create a new message instance and set up
            new_message = Message(
                    user_sent = TaskSeeker.objects.get(user=request.user.id).user,
                    user_received = Tasker.objects.get(user=_id).user,
                    booking = booking,
                    message = "Say hi to your next tasker!",
            )
            new_message.save()
            
            messages.add_message(request, messages.SUCCESS, 'Done! Your task has been booked!')
            return redirect(reverse('booking:booking-list', kwargs={'_id': request.user.id}))
    else:
        form = ScheduleBookingForm()

    return render(request, 'booking/booking.html', {'form': form, 'day_arr': day_arr, 'user_id': _id})

# Ajax request to get array of available times dynamically
def available_times_ajax(request, _id, category):
    day = int(request.GET.get('booking', None))
    user = request.GET.get('user', None)
    date = request.GET.get('date', None)

    day_dict = {0: 'SUN', 1: 'MON', 2: 'TUE', 3: 'WED', 4: 'THU', 5: 'FRI', 6: 'SAT'}
    available_times_arr = []
    booked_arr = []
    
    tasker_schedule = Schedule.objects.filter(day_of_week=day_dict[day]).first()
    tasker_booking = ScheduleBooking.objects.filter(tasker=user).first()

    if tasker_schedule is not None:
        available_times_arr = tasker_schedule.time_array()

    if tasker_booking is not None:
        booked_arr = tasker_booking.get_bookings(user, date)

    data = {
        'available': available_times_arr,   
        'booked': booked_arr,
    }

    return JsonResponse(data)

def tasker_reviews_ajax(request, _id):
    reviews = ScheduleBookingReview.objects.filter(schedule__tasker__user=_id)[:5]
    data = []

    for review in reviews:
        seeker = TaskSeeker.objects.get(user_id=review.schedule.seeker.user.id)
        picture = None

        try:
            picture = seeker.user.profile_picture.url
        except ValueError:
            picture = 'https://lh3.googleusercontent.com/proxy/1Ns5bl_A4oo3EiBoDQRXYoBQp8CwKzUPztOH-1LoQ1Y9Fq_Kh_MAWAPVHPM0ohlT4qPxuDAxYJRjkdloaqluDRs28c4DTzZKUlNH3XY'
            
        data.append({
            'id': review.id,
            'review': review.review,
            'created': review.created.strftime("%B %w, %Y"),
            'rating': review.rating,
            'seeker': seeker.user.first_name,
            'profile_url': picture
        })
    
    return JsonResponse({'data': data, 'user_id': _id })

templates/booking/_detail_seeker.html
{% load crispy_forms_tags %}
    
    <div class="row">
        <div class="col-md-6">
            <h3>Your tasker for this job: </h3>
            <div class="card-custom">
                <div class="picture-container">
                    <div class="picture">
                        <div class="profile-image" style="background-image: url({{ booking.tasker.user.profile_picture.url }})"></div>
                    </div>
                </div>
                <div class="info-1">
                   <div class="info-container">
                       <h2>{{ booking.tasker }}</h2>
                        <h3>￥{{ booking.price }} /hr</h3>
                   </div>
                </div>
                <div class="info-2">
                    
                    <p>Scheduled for:</p>
                    <p>{{ booking.booking }}</p>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            {% if booking.completed is False %}
            <h3>Has the job been finished? Leave a review!</h3>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}

                <input class="btn-custom-2 my-5" type="submit" value="Submit" style="margin: 0 auto;">
            </form>
            {% else %}
            <div class="detail-reviewed">
                <h3 class="text-center">This job has been marked as finished and you left a review.</h3>
                <h3 class="text-center mt-3">Thank you!</h3>
            </div>
            {% endif %}
        </div>
    </div>

templates/booking/_detail_tasker.html
<div class="row">
    <div class="col-md-6">
        <div class="card-custom">
            <div class="picture-container">
                <div class="picture">
                    <div class="profile-image" style="background-image: url({{ booking.seeker.user.profile_picture.url }})"></div>
                </div>
            </div>
            <div class="info-1">
               <div class="info-container">
                   <h2>{{ booking.seeker }}</h2>
                   <a href="{% url 'chat:my-messages' booking.id %}">{% if not booking.completed %}Message{% endif %}</a>
               </div>
            </div>
            <div class="info-2">
                
                <p>Scheduled for:</p>
                <p>{{ booking.booking }}</p>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card-custom" style="display: flex; flex-direction: column;">
            <h4>Task info</h4>
            <p><strong>Task Type: </strong>{{ booking.category }}</p>
            <p><strong>Price: </strong>￥{{ booking.price }} /hr</p>
            <p><strong>Location: </strong> {{ booking.seeker.user.address }}</p>
            <p><strong>Notes: </strong>{{ booking.notes }}</p>
            <p><strong>Completed: </strong>
                {% if booking.completed %}
                <i class="fas fa-check" style="color: green;"></i>
                <p><strong>Rating: </strong>{{ review.rating }}</p>
                <p><strong>Review: </strong>{{ review.review }}</p>
                {% else %}
                --
                {% endif %}
            </p>
        </div>

    </div>
</div>

templates/booking/booking.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    
    {% include 'utilities/_messages.html' %}

    <div class="container">
        <h2 class="mt-3 text-center">Choose your task date and start time</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="form-row justify-content-center my-5">
                <div class="form-group col-md6 mx-5">
                    {{ form.booking|as_crispy_field }}
                    <span id="booking-conf"></span>
                </div>
                <div class="form-group col-md6">
                    {{ form.notes|as_crispy_field }}
                </div>
            </div>
            <input type="submit" value="Select and continue" class="btn-custom-2" style="font-weight: 900; margin: 10px auto;">
        
        </form>
    </div>
{{ bookings }}

{% endblock %}


{% block scripts %}
<script>
    // https://xdsoft.net/jqplugins/datetimepicker/#disabledWeekDays
    // https://stackoverflow.com/questions/27173140/jquery-date-and-timepicker-different-time-on-specific-day


    $(function () {
        // Get current taskers full schedule as JSON
        // When a user clicks on a date, a check aginst the JSON obj will be done
        // If a schedule is found, allowTimes will be set based on the result of the check
        // Else, it is just the regular time schedule
        const confirmation = document.getElementById('booking-conf');
        var bookingsObj = {};
        var datePickerTime = function(currentDateTime) {
            let day = (currentDateTime.getUTCDate()).toString().padStart(2,0);
            let month = (currentDateTime.getUTCMonth() + 1).toString().padStart(2,0);
            let year = currentDateTime.getUTCFullYear();

            let fullDate = `${year}-${month}-${day}`
            let allowTimesArray = null
            let bookedArray = null
            const dummyThis = this

            let monthFull = currentDateTime.toLocaleString('default', { month: 'short' });
            let timeH = currentDateTime.getHours();
            let timeM = currentDateTime.getMinutes().toString().padStart(2,0);

            confirmation.innerHTML = `<p style="font-size: 1.25rem;">Request for: <strong>${monthFull} ${day}, ${timeH}:${timeM}</strong></p>`

            $.ajax({
                url: 'ajax/booking',
                data: {
                    'booking': currentDateTime.getDay(),
                    'user': {{ user_id }},
                    'date': fullDate,
                },
                dataType: 'json',
                success: function(data){
                    allowTimesArray = [...data.available]
                    bookedArray = [...data.booked]
                }
            })
            .done(function() {
                for(let i=0; i < allowTimesArray.length; i++){                    
                    if(allowTimesArray.includes(bookedArray[i])){
                        allowTimesArray.splice(allowTimesArray.indexOf(bookedArray[i]), 2)
                    } 
                }
                dummyThis.setOptions({
                    allowTimes: allowTimesArray
                })
            })
        };

      $("#id_booking").datetimepicker({
        format: 'd/m/Y H:i',
        inline: true,
        disabledWeekDays: {{ day_arr }},
        onChangeDateTime: datePickerTime,
      });

    });
</script>
{% endblock %}

templates/booking/booking_detail.html
{% extends 'base.html' %}

{% block content %}
<section id="booking-detail">
<div class="container">
    <h1 class="my-4">Booking Details</h1>
    {% if request.user.is_seeker %}
        {% include 'booking/_detail_seeker.html'%}
    {% endif %}

    {% if request.user.is_tasker %}
        {% include 'booking/_detail_tasker.html'%}
    {% endif %}

</div>

</section>

{% endblock %}

templates/booking/booking_list.html
{% extends 'base.html' %}

{% block content %}
<section id="booking-list">
<div class="container">
    <h1 class="my-3">Your bookings</h1>
    
    {% include 'utilities/_messages.html' %}

    <table class="table">
        <thead>
            <tr>
                <th scope="col">
                    {% if request.user.is_seeker %}
                    Tasker
                    {% else %}
                    Task Seeker
                    {% endif %}
                </th>
                <th scope="col">Scheduled</th>
                <th scope="col">Task Type</th>
                <th scope="col">Completed</th>
                <th scope="col">Details</th>
            </tr>
        </thead>
        <tbody>
            {% for booking in bookings %}
            <tr>
                <td>
                    {% if request.user.is_seeker %}
                    {{ booking.tasker }}
                    {% else %}
                    {{ booking.seeker }}
                    {% endif %}
                </td>
                <td>{{ booking.booking}}</td>
                <td>{{ booking.category }}</td>
                <td style="text-align: center; vertical-align: middle;">
                    {% if booking.completed %}
                    <i class="fas fa-check" style="color: green;"></i>
                    {% endif %}
                </td>
                <td><a href="{{ booking.get_absolute_url }}">View</a></td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>
</section>

{% endblock%}

templates/booking/booking_search.html
{% extends 'base.html' %}

{% block content %}
<section id="booking-search">
<div class="container">
    <h2 class="text-center my-4">Find {{ category_name|lower }} services in your area today!</h2>  
    <div class="row">
        <div class="search-form col-md-4">
            <form method="GET">
                <div class="search-form-container">
                    <div class="search-form-item"> 
                        <i class="fas fa-dollar-sign fa-lg"></i><span class="search-item-header">price</span>
                        <select class="form-control" name="price" id="price" style="margin-top: 10px;">
                            <option value="high">Price: Highest</option>
                            <option value="low">Price: Lowest</option>
                        </select>
                    </div>
                    <div class="search-form-item"> 
                        <i class="far fa-clock fa-lg"></i><span class="search-item-header">task time</span>
                        <div class="search-form-radio">
                            <div class="search-form-control">
                                <input type="radio" name="task-time" id="morning" value="morning">
                                <label for="morning">Morning (8am - 12pm)</label>
                            </div>
                            <div class="search-form-control">
                                <input type="radio" name="task-time" id="afternoon" value="afternoon">
                                <label for="afternoon">Afternoon (12pm - 5pm)</label>
                            </div>
                            <div class="search-form-control">
                                <input type="radio" name="task-time" id="evening" value="evening">
                                <label for="evening">Evening (5pm - 9:30pm)</label>
                            </div>
                        </div>
                    </div>

                    <button type="submit" class="btn-custom-1" style="width: 100%; margin: 10px 0 10px 0;">Sort</button>
                </div>

            </form>  
        </div>
        <div class="search-taskers col-md-8">
            {% for result in results %}
            <div class="card-custom">
                <div class="picture-container">
                    <div class="picture">
                        <div class="profile-image" style="background-image: url({{ result.tasker.user.profile_picture.url }})"></div>
                        <a href="#" class="mt-4 mb-4 my-modal" data-id="{{result.tasker.user.id}}" data-toggle="modal" data-target="#tasker-{{result.id}}">View Profile & Reviews</a>
                        <a href="{% url 'booking:schedule-booking' _id=result.tasker.user.id category=result.category %}" class="btn-custom-2">Select & Continue</a>
                    </div>
                </div>
                <div class="info-1">
                   <div class="info-container">
                       <h2>{{ result.tasker }}</h2>
                       <ul>
                           <li><i class="far fa-star"></i> {{ result.tasker.rating }} / 5 positive rating</li>
                           <li><i class="far fa-check-circle"></i> {{ result.tasker.completed }} tasks successfully completed</li>
                           <li><i class="fas fa-language"></i> {{ result.tasker.user.get_language }}</li>
                       </ul>
                   </div>
                   <div class="info-price">
                        <h3>￥{{ result.price }} /hr</h3>
                   </div>
                </div>
                <div class="info-2">
                    <p>{{ result.tasker.user.bio }}</p>
                </div>
            </div>
        
        <!-- Modal -->
        <div class="modal fade" id="tasker-{{result.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-body d-flex flex-column align-items-center">
                    <div class="profile-image" style="background-image: url({{ result.tasker.user.profile_picture.url }})"></div>
                    <h3 class="mt-3">{{ result.tasker }} ￥{{ result.price }} /hr</h3>
                    <div class="modal-info-container">
                        <div class="modal-info-item my-3">
                            <strong>I'm the right person for the job...</strong>
                            <p>{{ result.description }}</p>
                        </div>
                        <div class="modal-info-item my-3">
                            <strong>A bit more about me...</strong>
                            <p>{{ result.tasker.user.bio }}</p>
                        </div>
                        <hr>
                        <div data-id="{{result.tasker.user.id}}" class="modal-info-item my-3"></div>
                        <a style="display: block; text-align: center;" href="{% url 'user:tasker-profile' _id=result.tasker.user.id %}">See all reviews</a>
                    </div>
  
                </div>
                <div class="modal-footer">
                <button type="button" class="btn-custom-1" data-dismiss="modal">Close</button>
                </div>
            </div>
            </div>
        </div>

        {% endfor %}
        </div>
    </div>


</div>
</section>

{% block scripts %}

<script>


$(function () {

myModalLink = document.querySelectorAll('.my-modal');
allModals = document.querySelectorAll('.modal-info-item')

const ratingFunc = function(rating) {
    toNum = parseInt(rating);
    star_template = '<i class="fas fa-star" style="color: orange;"></i>';
    star_total = ''

    for(let i = 0; i <= rating - 1; i++) {
        star_total += star_template
    }

    return star_total
}

myModalLink.forEach(modal => {
        fetch(`ajax/reviews/${modal.dataset.id}/`)
            .then(response => response.json())
            .then(data => {
                allModals.forEach(e => {
                    if(parseInt(e.dataset.id) === data['user_id']) {
                        data['data'].forEach(review => {
                            e.innerHTML += `
                            <div class="review-container" style="display: flex; align-items: center;">
                                <div class="review-item">
                                    <div class="profile-image" style="background-image: url(${review.profile_url}); margin-right: 20px"></div>
                                </div>
                                <div class="review-item">
                                    <div>${ratingFunc(review.rating)}</div>                                    
                                    <div style="margin-top: 5px;">"${review.review}"</div>
                                    <div style="font-size: 0.8rem; color: grey; margin-top: 5px;">${review.seeker}, ${review.created}</div>
                                </div>
                                <br>
                                <hr>
                            </div>
                            `
                        })
                    }
                })
            })
})

})

</script>
{% endblock %}

{% endblock %}