chat/urls.py
from django.urls import path
from .views import messages, messages_json, send_message_json, message_home

app_name = 'chat'

urlpatterns = [
    path('', message_home, name="message-home"),
    path('<int:booking_id>', messages, name="my-messages"), 
    path('messages/json/<int:booking_id>', messages_json, name="json-messages"),
    path('messages/json/send_message/<int:booking_id>', send_message_json, name="messages-send")

]

taskusagi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls')),
    path('bookings/', include('booking.urls')),
    path('chat/', include('chat.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from users.models import CustomUser
from booking.models import ScheduleBooking

class Message(models.Model):
    user_sent = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='sent_messages')
    user_received = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='received_messages')
    booking = models.ForeignKey(ScheduleBooking, on_delete=models.CASCADE)
    message_created = models.DateTimeField(auto_now_add=True)
    message = models.TextField(max_length=200)
    message_read = models.BooleanField(default=False)

    @classmethod
    def get_unread_messages(cls, id):
        user = CustomUser.objects.filter(id=id).first()
        sent_messages = cls.objects.filter(user_sent=user, message_read=False).count()
        received_messages = cls.objects.filter(user_received=user, message_read=False).count()

        return sent_messages + received_messages

    @classmethod
    def get_messages(cls, booking):
        data = []
        booking_instance = cls.objects.filter(booking=booking).order_by('message_created')

        for item in booking_instance:
            data.append({
                'id': item.id,
                'sent': {
                    'id': item.user_sent.id,
                    'name': item.user_sent.get_full_name()
                },
                'received': {
                    'id': item.user_received.id,
                    'name': item.user_received.get_full_name()
                },
                'message': item.message,
                'created': item.message_created,
            })
        
        return data

    def __str__(self):
        return 'Message Instance | {} '.format(self.booking)

chat/forms.py
from django import forms
from .models import Message

class MessageForm(forms.Form):
    message = forms.CharField(label='', max_length=100, required=False)
    

chat/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse
from booking.models import ScheduleBooking
from users.models import CustomUser
from .models import Message
from .forms import MessageForm
from .decorators import sender_or_receiver
import json

def message_home(request):
    contact_list = None

    if request.user.is_tasker:
        contact_list = ScheduleBooking.objects.filter(tasker=request.user.id)
    else:
        contact_list = ScheduleBooking.objects.filter(seeker=request.user.id)

    return render(request, 'chat/message_home.html', {'contact_list': contact_list})

@sender_or_receiver
def messages(request, booking_id):
    form = MessageForm()
    booking = ScheduleBooking.objects.get(id=booking_id)
    messages = Message.get_messages(booking=booking)
    receiver_id = booking.seeker.user.id if request.user.id == booking.tasker.user.id else booking.tasker.user.id
    contact_list = None 

    if booking.message_set.latest('message_created').user_received == request.user:
        instance = booking.message_set.latest('message_created')
        instance.message_read=True
        instance.save()

    if request.user.is_tasker:
        contact_list = ScheduleBooking.objects.filter(tasker=request.user.id)
    else:
        contact_list = ScheduleBooking.objects.filter(seeker=request.user.id)

    return render(request, 'chat/my_messages.html', {'booking_id': booking_id, 
                                                    'form': form,
                                                    'receiver_id': receiver_id,
                                                    'contact_list': contact_list
                                                    })

@sender_or_receiver
def messages_json(request, booking_id):
    booking = ScheduleBooking.objects.get(id=booking_id)
    messages = Message.get_messages(booking=booking)

    return JsonResponse(messages, safe=False)

@sender_or_receiver
def send_message_json(request, booking_id):
    booking = ScheduleBooking.objects.get(id=booking_id)

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            data = json.loads(request.body)
            Message.objects.create(
                    user_sent=request.user, 
                    user_received=CustomUser.objects.get(id=data['receiver_id']),
                    booking=booking,
                    message=data['message']
            )
            return JsonResponse(data, safe=False)
    
    return JsonResponse({}, safe=False)

templates/chat/_contactlist.html
    <div class="messages-container">
        <div class="chat-list">
            {% if user.is_tasker %}
                {% for contact in contact_list %}
                <a style="color: inherit;" href="{% url 'chat:my-messages' contact.id %}">
                    <div class="chat-list-item-container">
                        <div class="chat-list-item-1">
                            <div class="profile-image-sm" style="background-image: url({{ contact.seeker.user.profile_picture.url }})"></div>
                            <div class="chat-list-item">
                                <p style="{% if not contact.get_most_recent_message.message_read %}font-weight: 900;{% endif %}">{{ contact.seeker }}</p>
                                <p class="chat-list-item-faded" style="{% if not contact.get_most_recent_message.message_read %}font-weight: 900;{% endif %}">{{ contact.get_most_recent_message.message|truncatechars:10 }}</p>
                            </div>
                        </div>
                        <div class="chat-list-item-2">
                            <div class="chat-list-item-date">
                                <p class="chat-list-item-faded">{{ contact.get_most_recent_message.message_created|date:"g:i a" }}</p>
                            </div>
                        </div>
                    </div>
                </a>
                {% endfor %}
            {% else %}
                {% for contact in contact_list %}
                <a style="color: inherit;" href="{% url 'chat:my-messages' contact.id %}">
                    <div class="chat-list-item-container">
                        <div class="chat-list-item-1">
                            <div class="profile-image-sm" style="background-image: url({{ contact.tasker.user.profile_picture.url }})"></div>
                            <div class="chat-list-item">
                                <p style="{% if not contact.get_most_recent_message.message_read %}font-weight: 900;{% endif %}">{{ contact.tasker }}</p>
                                <p class="chat-list-item-faded" style="{% if not contact.get_most_recent_message.message_read %}font-weight: 900;{% endif %}">{{ contact.get_most_recent_message.message|truncatechars:10 }}</p>
                            </div>
                        </div>
                        <div class="chat-list-item-2">
                            <div class="chat-list-item-date">
                                <p class="chat-list-item-faded">{{ contact.get_most_recent_message.message_created|date:"g:i a" }}</p>
                            </div>
                        </div>
                    </div>
                </a>
                {% endfor %}
            {% endif %}
        </div>

templates/chat/message_home.html
{% extends 'base.html' %}

{% block content %}

    <section id="messages">
        {% include 'chat/_contactlist.html' %}
    </section>
    
{% endblock content %}

templates/chat/my_messages.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<section id="messages">
    
        {% include 'chat/_contactlist.html' %}

        <div class="chat-window-container">
            <div class="chat-window">
                <div class="messages"></div>
            </div>
            <div class="chat-send-form">
                <form method="POST" id="send-message">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-10">
                            {{ form.message|as_crispy_field }}
                        </div>
                        <input class="btn-custom-1"type="submit" value="Submit">
                    </div>
                </form>
            </div>
        </div>
        
    </div>
</section>
    
{% endblock %}

{% block scripts %}
<script>

    const messagesContainer = document.querySelector('.messages');
    const booking_id = {{ booking_id }}
    const receiverId = {{ receiver_id }}
    const senderId = {{ request.user.id }}
    const chatWindow = document.querySelector('.chat-window-container')
    let messagesId;
    
    // RECEIVE messages

    fetch(`messages/json/${booking_id}`)
        .then(response => response.json())
        .then(data => {
            let messages = [...data]
            // Set up initial messages
            messages.forEach(message => {
                console.log(message)
                if(message.sent['id'] === senderId){
                    messagesContainer.innerHTML += `
                        <div class="chat-sender">${message.message}</div>`
                } else {
                    messagesContainer.innerHTML += `
                        <div class="chat-receiver">${message.message}</div>`
                }
                })
            // Messages ID that will be used to filter new messages
            messagesId = messages.map(message => {
                return message.id
            })

        }
        )

    // Ajax call every 3 seconds to check for new messages and update template
    setInterval(function() {


    fetch(`messages/json/${booking_id}`)
        .then(response => response.json())
        .then(data => {
            data.forEach(new_message => {
                if(messagesId.indexOf(new_message.id) == -1) {
                    messagesId.push(new_message.id)

                if(new_message.sent['id'] === senderId){
                    messagesContainer.innerHTML += `
                        <div class="chat-sender">${new_message.message}</div>`
                } else {
                    messagesContainer.innerHTML += `
                        <div class="chat-receiver">${new_message.message}</div>`
                }
                }
            })
            document.querySelector('.btn-custom-1').scrollTop = document.querySelector('.btn-custom-1').scrollHeight; 
            console.log(document.querySelector('.btn-custom-1').scrollTop)
        }
        )
    }, 3000) 

    // SEND new message

    const submitMessage = document.querySelector('#send-message');
    
    submitMessage.addEventListener('submit', function(e) {
        const message = document.querySelector('#id_message').value;
        data = {
            'message': message,
            'receiver_id': receiverId,
        }
        submitMessage.reset();

        e.preventDefault()
        fetch(`messages/json/send_message/${booking_id}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken
            },

            body: JSON.stringify(data)
        })
        .then(response => response.json())
        .then(data => console.log(data))
    })

</script>

{% endblock %}