booking/urls.py
from django.urls import path
from .views import booking_list, schedule_booking, available_times_ajax, booking_search, booking_detail, tasker_reviews_ajax

app_name = 'booking'

urlpatterns = [
    path('booking_list/<int:_id>', booking_list, name="booking-list"),
    path('booking_search/<slug:category>', booking_search, name="booking-search"),
    path('booking_schedule/<int:_id>/<str:category>/', schedule_booking, name="schedule-booking"),
    path('booking_schedule/<int:_id>/<str:category>/ajax/booking', available_times_ajax, name="booking-times"),
    path('booking_detail/<int:id>/', booking_detail, name="booking-detail"),
    path('booking_search/ajax/reviews/<int:_id>/', tasker_reviews_ajax, name="tasker-reviews")
]

chat/urls.py
from django.urls import path
from .views import messages, messages_json, send_message_json, message_home

app_name = 'chat'

urlpatterns = [
    path('', message_home, name="message-home"),
    path('<int:booking_id>', messages, name="my-messages"), 
    path('messages/json/<int:booking_id>', messages_json, name="json-messages"),
    path('messages/json/send_message/<int:booking_id>', send_message_json, name="messages-send")

]

taskusagi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls')),
    path('bookings/', include('booking.urls')),
    path('chat/', include('chat.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import SignUpView, SeekerSignUpView, TaskerSignUpView, edit_profile, tasks, task_delete, dashboard, tasker_schedule,tasker_schedule_delete,todo_delete, tasker_profile_view

app_name = 'user'

urlpatterns = [
    path('dashboard/', dashboard, name="dashboard"), 
    path('dashboard/<int:todo_id>/', dashboard, name="dashboard"), 
    path('signup/', SignUpView.as_view(), name='signup'),
    path('seeker_signup/', SeekerSignUpView.as_view(), name='seeker-signup'),
    path('tasker_signup/', TaskerSignUpView.as_view(), name='tasker-signup'),
    path('profile_edit/', edit_profile, name='profile_edit'),
    path('tasker_tasks/', tasks, name='tasks'),
    path('tasker_schedule/', tasker_schedule, name='tasker-schedule'),
    path('tasker_task_delete/<int:_id>', task_delete, name='task-delete'),
    path('tasker_schedule_delete/<int:_id>', tasker_schedule_delete, name='tasker-schedule-delete'),
    path('tasker_profile/<int:_id>', tasker_profile_view, name='tasker-profile'),
    path('todo_delete/<int:id>/', todo_delete, name='todo-delete')
]

booking/models.py
import functools
from django.db import models
from django.core import serializers
from users.models import Tasker, TaskSeeker
from django.urls import reverse
from datetime import datetime


class ScheduleBooking(models.Model):
    tasker = models.ForeignKey('users.Tasker', on_delete=models.CASCADE)
    seeker = models.ForeignKey('users.TaskSeeker', on_delete=models.CASCADE)
    category = models.CharField(max_length=50)
    booking = models.DateTimeField()
    price = models.IntegerField()
    notes = models.TextField(max_length=200)
    completed = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('booking:booking-detail', kwargs={'id': self.id })

    @property
    def get_most_recent_message(self):
        return self.message_set.latest('message_created')

    @classmethod
    def get_bookings(cls, _id, date):
        test = cls.objects.filter(tasker=_id, booking__date=date)
        bookings_dict = []
        
        for item in test:
            bookings_dict.append(item.booking.time().strftime("%H:%M"))

        return bookings_dict

    @classmethod
    def get_month_earnings(cls, tasker):
        current_month_schedules = cls.objects.filter(tasker=tasker, booking__month=datetime.today().month)
        bookings_list = []
        for booking in current_month_schedules:
            bookings_list.append(booking.price)
            
        return functools.reduce(lambda a,b: a+b, bookings_list) if len(bookings_list) else 0

    def __str__(self):
        return 'Tasker: {}, Seeker: {}, Booking: {}'.format(self.tasker, self.seeker, self.booking)

REVIEW_CHOICES = [
    ('1', 1),
    ('2', 2),
    ('3', 3),
    ('4', 4),
    ('5', 5)
]

class ScheduleBookingReview(models.Model):
    schedule = models.ForeignKey('ScheduleBooking', on_delete=models.CASCADE)
    review = models.TextField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)
    rating = models.CharField(
        max_length=1,
        choices=REVIEW_CHOICES,
        default=3
    )

    def __str__(self):
        return 'Schedule Review: {}, Rating: {}'.format(self.schedule, self.rating)

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Tasker, TaskSeeker, TaskCanDo, Schedule
from django import forms
from django.core.exceptions import ValidationError

from django.core.validators import RegexValidator

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = get_user_model()
        fields = ('username', 'email',)

class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email', 'address', 'language', 'nationality', 'bio', 'profile_picture', 'phone_num')

    def clean_phone_num(self):
        phone_num = self.cleaned_data['phone_num']
        regex = RegexValidator('^(0([1-9]{1}-?[1-9]\d{3}|[1-9]{2}-?\d{3}|[1-9]{2}\d{1}-?\d{2}|[1-9]{2}\d{2}-?\d{1})-?\d{4}|0[789]0-?\d{4}-?\d{4}|050-?\d{4}-?\d{4})$', 'Invalid phone number')
        if regex(phone_num) is not None:
            raise ValidationError('Invalid phone number')

        return phone_num


class TaskerSignUpForm(UserCreationForm):

    class Meta(UserCreationForm):
        
        model = get_user_model()
        fields = ('username', 'email',)

    def save(self):
        user = super().save(commit=False)
        user.is_tasker = True
        user.save()
        Tasker.objects.create(user=user)
        return user

class SeekerSignUpForm(UserCreationForm):

    class Meta(UserCreationForm):
        
        model = get_user_model()
        fields = ('username', 'email',)

    def save(self):
        user = super().save(commit=False)
        user.is_seeker = True
        user.save()
        TaskSeeker.objects.create(user=user)
        return user

class TaskCreateForm(forms.ModelForm):
    
    class Meta:
        model = TaskCanDo
        fields = ['category', 'description', 'price']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(TaskCreateForm, self).__init__(*args,**kwargs)

    def clean_category(self):
        category = self.cleaned_data['category']
        tasks = TaskCanDo.objects.filter(tasker=self.user.id)
        
        for task in tasks:
            if category == task.category:
                raise ValidationError('You can only have one task type registered at a time')

        return category


class TaskDeleteForm(forms.ModelForm):

    class Meta:
        model = TaskCanDo
        fields = []

class ScheduleCreateForm(forms.ModelForm):

    class Meta:
        model = Schedule
        fields = ['day_of_week', 'start_time', 'end_time']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(ScheduleCreateForm, self).__init__(*args,**kwargs)

    def clean(self):
        cleaned_data = super(ScheduleCreateForm, self).clean()
        start = cleaned_data.get('start_time', '')
        end = cleaned_data.get('end_time', '')

        if end < start:
            raise ValidationError('You can\'t have the end before the start!!')

        return cleaned_data

    def clean_day_of_week(self):
        qs = Schedule.objects.filter(tasker=self.user.id)
        day = self.cleaned_data['day_of_week']
        tasker_days = [day.day_of_week for day in qs]

        if day in tasker_days:
            raise ValidationError('You can only have one time slot for each day')

        return day

class ToDoForm(forms.Form):
    todo = forms.CharField(label="", max_length=150)

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic 
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from datetime import datetime, timedelta
import random

from users.forms import CustomUserCreationForm, TaskerSignUpForm, CustomUserChangeForm, TaskCreateForm, TaskDeleteForm, ScheduleCreateForm, SeekerSignUpForm, ToDoForm
from users.models import Tasker, TaskSeeker, CustomUser, TaskCanDo, Schedule, ToDo
from booking.models import ScheduleBooking, ScheduleBookingReview
from chat.models import Message
from .decorators import seeker_required, tasker_required

class SignUpView(generic.TemplateView):
    template_name = 'signup.html'

class SeekerSignUpView(generic.CreateView):
    form_class = SeekerSignUpForm
    template_name = 'registration/seeker_signup.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('user:profile_edit')

class TaskerSignUpView(generic.CreateView):
    form_class = TaskerSignUpForm
    template_name = 'registration/tasker_signup.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        messages.add_message(self.request, messages.INFO, 'Please complete your registration!')
        return redirect('user:profile_edit')

@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Profile updated!')
            return redirect('user:profile_edit')
    else:
        form = CustomUserChangeForm(instance=request.user)

    return render(request, 'users/profile_edit.html', {'form': form})

@user_passes_test(tasker_required)
@login_required
def tasks(request):
    tasks = TaskCanDo.objects.filter(tasker=request.user.id)

    if request.method == 'POST':
        form = TaskCreateForm(request.POST, user=request.user)
        if form.is_valid():
            task = form.save(commit=False)
            task.tasker = Tasker.objects.filter(user=request.user.id)[0]
            task.save()
    else:
        form = TaskCreateForm(user=request.user)


    return render(request, 'users/tasks.html', {'tasks': tasks,
                                                'form': form,
                                                })
@user_passes_test(tasker_required)
@login_required
def task_delete(request, _id):
    obj = TaskCanDo.objects.filter(id=_id, tasker=request.user.id)

    if request.method == 'POST':
        obj.delete()
    
    return redirect('user:tasks')

@user_passes_test(tasker_required)
@login_required
def tasker_schedule(request):
    schedule_list = Schedule.objects.filter(tasker=request.user.id)

    if request.method == 'POST':
        form = ScheduleCreateForm(request.POST, user=request.user)
        if form.is_valid():
            schedule = form.save(commit=False)
            schedule.day_of_week = form.cleaned_data['day_of_week']
            schedule.start_time = form.cleaned_data['start_time']
            schedule.end_time = form.cleaned_data['end_time']
            schedule.tasker = Tasker.objects.filter(user=request.user.id)[0]

            schedule.save()
            messages.add_message(request, messages.SUCCESS, 'You added a new task!')
            return redirect('user:tasker-schedule')
    else:
        form = ScheduleCreateForm(user=request.user)

    return render(request, 'users/tasker_schedule.html', {'form': form, 'schedule_list': schedule_list})

@user_passes_test(tasker_required)
@login_required
def tasker_schedule_delete(request, _id):
    obj = Schedule.objects.get(id=_id, tasker=request.user.id)

    if request.method == 'POST':
        obj.delete()

    return redirect('user:tasker-schedule')

@login_required
def dashboard(request, todo_id=None):
    categories = TaskCanDo.TASK_CHOICES
    upcoming_tasks = None
    month_earnings = None
    todo_list = None
    form = None
    today = datetime.today()
    days_check = datetime.today() - timedelta(days=360)
    new_taskers = []
    unread_messages = None

    taskers_q = Tasker.objects.filter(user__date_joined__range=(days_check, today))
    rand_arr = random.sample(range(0,len(taskers_q)), 3)
    
    for i in range(0,3):
        new_taskers.append(taskers_q[rand_arr[i]])

    if request.user.is_tasker:
        upcoming_tasks = ScheduleBooking.objects.filter(tasker=request.user.tasker, completed=False, booking__range=(
                                                             datetime.today().strftime("%Y-%m-%d"), (datetime.today() + timedelta(days=30)) 
                                                             )).order_by('booking')[:3]
        month_earnings = ScheduleBooking.get_month_earnings(tasker=request.user.tasker)
        unread_messages = Message.get_unread_messages(id=request.user.id)

    if request.user.is_seeker:
        if request.method == 'POST':
            form = ToDoForm(request.POST)
            if form.is_valid():
                ToDo.objects.create(
                    seeker=request.user.taskseeker,
                    todo=form.cleaned_data['todo']
                )
                return redirect('user:dashboard')
        else:
            if todo_id:
                edit_todo = ToDo.objects.get(id=todo_id)
                form = ToDoForm(instance=edit_todo)
            else:
                form = ToDoForm()

        todo_list = ToDo.objects.filter(seeker=request.user.taskseeker)
        
    return render(request, 'dashboard.html', {'categories': categories, 
                                                'upcoming_tasks': upcoming_tasks, 
                                                'month_earnings': month_earnings, 
                                                'form': form, 
                                                'todo_list': todo_list,
                                                'new_taskers': new_taskers,
                                                'unread_messages': unread_messages
                                                })

@login_required
def todo_delete(request, id):
    obj = ToDo.objects.get(id=id, seeker=request.user.taskseeker)

    if request.method == 'POST':
        obj.delete()

    return redirect('user:dashboard')

@login_required
def tasker_profile_view(request, _id):
    tasker = Tasker.objects.filter(user=_id).first()
    task_can_do = TaskCanDo.objects.filter(tasker__user=_id)
    reviews = ScheduleBookingReview.objects.filter(schedule__tasker__user=_id)

    return render(request, 'users/tasker_profile.html', {'tasker': tasker, 
                                                        'task_can_do': task_can_do,
                                                        'reviews': reviews
                                                        })

templates/users/_seekerdash.html
{% load static %}
{% load crispy_forms_tags %}

<div class="dashboard-tasks-container">
    <div class="next-task-container">
    <h2 class="text-center mb-5 mt-5">What's your next task?</h2>
        <div class="dashboard-tasks-links">
            {% for category in categories %}
                <a class="btn-custom-1" href="{% url 'booking:booking-search' category.0 %}">{{ category.1|title }}</a>
            {% endfor %}
        </div>
        <div class="image-container">
            <img class="dashboard-tool" src="{% static 'taskusagi/img/tool.svg' %}" alt="">
        </div>
    </div>

        <div class="todo-container">
            <h2 class="todo-header">What else is on your to-do list?</h2>
            {% for todo in todo_list %}
            <div class="todo-item-container">
                <p class="todo-item">
                    {{ todo.todo }}
                </p> 
                <form action="{% url 'user:todo-delete' todo.id %}" method="POST" >
                    {% csrf_token %}
                    <input type="submit" class="todo-delete" value="x"">
                </form>
            </div>


            {% endfor %}
            <div class="todo-submit-container">
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="+" class="todo-submit">
                </form>
            </div>

        </div>
        <h2 class="mt-5 mb-5">Support our newest taskers!</h2>

        <div class="tasker-card-container">
            {% for tasker in new_taskers %}
            <div class="card-custom-2">
                <div class="info-1">
                   <div class="info-container">
                       <h2 style="text-align: center;">{{ tasker }}</h2>
                       <div class="picture-container" style="margin: 1rem 0;">
                        <div class="picture">
                            <div class="profile-image" style="background-image: url({{ tasker.user.profile_picture.url }})"></div>
                        </div>
                    </div>
                       <ul>
                           <li><i class="far fa-star"></i> {{ tasker.rating }} / 5 positive rating</li>
                           <li><i class="far fa-check-circle"></i> {{ tasker.completed }} tasks successfully completed</li>
                           <li><i class="fas fa-language"></i> {{ tasker.user.get_language }}</li>
                       </ul>
                   </div>
                </div>
                <div class="info-2">
                    <p>{{ tasker.user.bio|truncatechars:80 }}</p>
                </div>
                <div class="info-3 my-4">
                    <a href="{% url 'user:tasker-profile' tasker.user.id %}">View tasker profile</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

templates/users/_taskerdash.html
{% load static %}
{% load crispy_forms_tags %}

<h1 class="my-5 text-center">Welcome back, {{ user.first_name }}!</h1> 
<div class="container">
    <div class="row">
        <div class="col-md-6 my-3">
            <div class="wrapper">
                <div class="dash-item" style="margin: 0;">
                    <i class="fas fa-yen-sign fa-3x my-3"></i>
                    <h3>You've made ￥{{ month_earnings }} this month!</h3>
                </div>
                <div class="dash-item">
                    <i class="fas fa-tasks fa-3x my-3"></i>
                    <h3>You've completed {{ user.tasker.completed }} tasks in total!</h3>
                </div>
                <div class="dash-item">
                    <i class="far fa-envelope fa-3x my-3"></i>
                    <h3>
                    {% if  unread_messages %}
                        You have {{ unread_messages }} new message{{ unread_messages|pluralize }}
                    {% else %}
                        You have no new messages!
                    {% endif %}    
                    </h3>
                </div>
            </div>
        </div>
        <div class="upcoming-jobs col-md-6 my-3">
            {% if upcoming_tasks %}
            <h3>Upcoming jobs</h3>
            {% for task in upcoming_tasks %}
            <div class="card-custom">
                <div class="picture-container">
                    <div class="picture">
                        <div class="profile-image" style="background-image: url({{ task.seeker.user.profile_picture.url }})"></div>
                    </div>
                </div>
                <div class="info-1">
                    <div class="info-container">
                        <p><strong>Client:</strong> {{ task.seeker }}</p>
                        <p><strong>Task Type:</strong> {{ task.category }}</p>
                        <p><strong>Time:</strong> {{task.booking}}</p>
                        <a href="{{ task.get_absolute_url }}">Click for more info</a>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h3>You have no upcoming jobs</h3>
        {% endif %}
        </div>
    </div>
</div>

templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h2 class="mt-5">Edit your profile</h2>

    {% include 'utilities/_messages.html' %}
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6">
                {{ form.username|as_crispy_field }}
            </div>
            
            <div class="form-group col-md-6">
                {{ form.email|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                {{ form.first_name|as_crispy_field }}
            </div>

            <div class="form-group col-md-6">
                {{ form.last_name|as_crispy_field }}
            </div>
        </div>
        {{ form.address|as_crispy_field }}
        <div class="form-row">
            <div class="form-group col-md-6">
                {{ form.language|as_crispy_field }}
            </div>

            <div class="form-group col-md-6">
                {{ form.nationality|as_crispy_field }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                {{ form.bio|as_crispy_field }}
            </div>
            <div class="form-group col-md-6">
                {{ form.profile_picture|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                {{ form.phone_num|as_crispy_field }}
            </div>
            <div class="form-group col-md-6">
                {{ form.password|as_crispy_field }}
            </div>
        </div>
        <input type="submit" value="Update" class="mb-5 btn-custom-1" style="margin-left: 0;">
    </form>
</div>


{% endblock %}

templates/users/tasker_profile.html
{% extends 'base.html' %}

{% block content %}

<section id="tasker-profile">
    <div class="container">
        <h1 class="mt-5">{{ tasker }}'s profile </h1>

        <div class="row">
            <div class="col-md-12">
                <div class="card-custom-2">
                    <div class="info-1">
                       <div class="info-container">
                           <h2 style="text-align: center;">{{ tasker }}</h2>
                           <div class="picture-container" style="margin: 1rem 0;">
                            <div class="picture">
                                <div class="profile-image" style="background-image: url({{ tasker.user.profile_picture.url }}); width: 225px; height: 225px; border-radius: 50%;"></div>
                            </div>
                        </div>
                           <ul>
                               <li><i class="far fa-star"></i> {{ tasker.rating }} / 5 positive rating</li>
                               <li><i class="far fa-check-circle"></i> {{ tasker.completed }} tasks successfully completed</li>
                               <li><i class="fas fa-language"></i> {{ tasker.user.get_language }}</li>
                           </ul>
                       </div>
                    </div>
                    <div class="info-2">
                        <h4 class="mt-4">A bit about me...</h4>
                        <p>{{ tasker.user.bio }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card-custom-2">
                    <h2 class="text-center">Services offered:</h2>
                    <div class="info-container-detail">
                            {% for task in task_can_do %}
                            <div class="info-detail-item">
                                <div class="header-container">
                                    <h4>{{ task.get_category_display }}</h4>
                                    <p>{{ task.description }}</p>
                                </div>
                                <a class="btn-custom-1 ml-5" style="display: flex; align-items: center;" href="{% url 'booking:schedule-booking' _id=tasker.user.id category=task.category %}">Select for ￥{{ task.price }} /hr</a>
                            </div>
                            <hr>
                            {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card-custom-2" style="display: block;">
                    <h3 class="text-center my-3">Reviews</h3>
                    <div class="review-container" style="display: flex; flex-direction: column;">
                        {% for review in reviews %}
                        <div class="review-item-wrapper my-2" style="display: flex; align-items: center;">
                            <div class="review-item">
                                <div class="profile-image" style="background-image: url({{review.schedule.seeker.user.profile_picture.url}}); margin-right: 20px"></div>
                            </div>
                            <div class="review-item">
                                <div class="star-rating" data-rating="{{ review.rating }}" data-category="{{ review.schedule.category }}"></div>                                    
                                <div style="margin-top: 5px;">"{{ review.review }}"</div>
                                <div style="font-size: 0.8rem; color: grey; margin-top: 5px;">{{ review.schedule.seeker }}, {{ review.created }}</div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% block scripts %}
<script>

const ratingDiv = document.querySelectorAll('.star-rating');

const ratingFunc = function(rating) {
    toNum = parseInt(rating);
    star_template = '<i class="fas fa-star" style="color: orange;"></i>';
    star_total = ''

    for(let i = 0; i <= rating - 1; i++) {
        star_total += star_template
    }

    return star_total
}

ratingDiv.forEach(e => {
    e.innerHTML = `<strong>${e.dataset.category}:</strong> ${ratingFunc(e.dataset.rating)}`
})

</script>
{% endblock %}

{% endblock %}

templates/users/tasker_schedule.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<section id="tasker-schedule">
    <div class="container">
        <h1 class="my-5">Your current schedule: </h1>
        <div class="schedule-wrapper">
            {% for schedule in schedule_list %}
            <div class="schedule-item">
                <div class="items">
                    <p><strong>Day: </strong>{{ schedule.get_day_of_week_display }}</p>
                    <p><strong>Start time: </strong> {{schedule.start_time}}</p>
                    <p><strong>End Time: </strong> {{ schedule.end_time }}</p>  
                </div>
                <form action="{% url 'user:tasker-schedule-delete' schedule.id %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="x" class="btn-custom-3">
                </form>
            </div>
        {% endfor %}
        </div>
        <h3 class="my-5">Register a new schedule time</h3>
        <form method="POST">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-4">
                    {{ form.day_of_week|as_crispy_field}}
                </div>
                <div class="form-group col-md-4">
                    {{ form.start_time|as_crispy_field}}
                </div>
                <div class="form-group col-md-4">
                    {{ form.end_time|as_crispy_field}}
                </div>
            </div>
            <input class="btn-custom-2"type="submit" value="Add new schedule">
        </form>
    </div>
    
</section>

{% endblock %}

templates/users/tasks.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<section id="tasks">
    <div class="container">
        <h2 class="my-5">Your currently registered tasks</h2>
        <div class="task-card-wrapper">
            {% for task in tasks %}
            <div class="task-card">
                <h3>{{ task.get_category_display }}</h3>
                <h4>￥{{ task.price }} /hr</h4>
                <p class="my-2">{{ task.description }}</p>
                <form action="{% url 'user:task-delete' task.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn-custom-1 my-3" type="submit">Delete</button>
                </form>
            </div>
        {% endfor %}
        </div>

        <div class="my-5">
            <h2>Add a new task</h2>
            <form method="POST" class="mt-5">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        {{ form.category|as_crispy_field }}
                        {{ form.price|as_crispy_field }}
                        <input class="btn-custom-2" type="submit" value="Add Task">
                    </div>
                    <div class="form-group col-md-6">
                        {{ form.description|as_crispy_field }}
                    </div>
                </div>

            </form>
        </div>
    </div>
</section>

{% endblock %}